- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.gnupg/gpg-agent.conf: gpg-agent.conf
    ~/.hammerspoon:
    ~/.hgrc_local:
    ~/.name:
    ~/.ocamlinit:
    ~/.shell_local_after:
    ~/.shell_local_before:
    ~/.ssh/config: ssh/config
    ~/.vimrc_local:
    ~/.zshrc_local_after:
    ~/.iTerm2: iTerm2  

- shell:
  - git submodule sync --recursive
  - git update-submodules # after linking ~/.gitconfig
  - ./macos
